dist: precise
language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
  - node_modules
install: true
script:
 - 'if [ $TEST_SUITE = "simple" ]; then tasks/e2e-simple.sh; fi'
 - 'if [ $TEST_SUITE = "installs" ]; then tasks/e2e-installs.sh; fi'
 - 'if [ $TEST_SUITE = "kitchensink" ]; then tasks/e2e-kitchensink.sh; fi'
env:
  global:
    - USE_YARN=no