export const BOARD_SET_CELLS = 'BOARD_SET_CELLS';
export const BOARD_SET_TIMER = 'BOARD_SET_TIMER';
export const BOARD_TOGGLE_RUNNING = 'BOARD_TOGGLE_RUNNING';
export const BOARD_TOGGLE_NEXT_ROUND = 'BOARD_TOGGLE_NEXT_ROUND';
export const BOARD_RESET = 'BOARD_RESET';
export const BOARD_GAME_OVER = 'BOARD_GAME_OVER';
